Move Aggregation Pipeline docs to its own page (with Map Reduce)
mongodb/mongoid pull request #5308
Opened 2022-06-07 19:57 UTC by johnnyshields

2022-06-08 19:29 UTC, p-mongo requested changes
Hi @johnnyshields , thank you for the PR.

Please only move the aggregation pipeline documentation without making any other changes. Leave map/reduce documentation where it is, etc.

2022-06-10 03:53 UTC, johnnyshields commented
OK done. Map/reduce reverted.

2022-06-10 14:26 UTC, p-mongo requested changes

2022-06-10 14:26 UTC, p-mongo commented on docs/reference/aggregation-pipeline.txt
> +Since the aggregation pipeline is implemented by the MongoDB Ruby Driver
Please return this paragraph to its original version.

2022-06-10 14:26 UTC, p-mongo commented on docs/reference/aggregation-pipeline.txt
> +.. _aggregation-pipeline-dsl:
Please return this label to what it was.

2022-06-10 14:26 UTC, p-mongo commented on docs/reference/aggregation-pipeline.txt
> +We could query which states a participant visited:
Return this to what it was.

2022-06-10 14:27 UTC, p-mongo commented on docs/reference/aggregation-pipeline.txt
> +Aggregation Pipeline DSL
This heading should also be returned to what it was.

2022-06-13 00:09 UTC, johnnyshields commented
@p-mongo my minor changes here add clarity to the documentation, there is no reason to revert them in my opinion. You're welcome to take over this PR and revert them if you'd like.

2022-06-16 19:58 UTC, p-mongo commented
Hi @johnnyshields ,

Removing text (as you have done with the headings and labels) does not add context. Removing text could potentially add clarity, but because there isn't a clear diff for the text changes (due to the entirety of text being moved from one file to another) this change is not reviewable.

Renaming labels breaks links to them.

I moved the documentation in https://github.com/mongodb/mongoid/pull/5320 without making further changes.

2022-06-16 19:58 UTC, closed without merging

2022-06-16 20:58 UTC, johnnyshields commented
OK, fair enough. I'll see if any of these changes can be merged in as a separate PR later.