MONGOID-5388 - Add Index wildcard_projection option and test for wildcard index
mongodb/mongoid pull request #5328
Opened 2022-06-18 00:00 UTC by johnnyshields

2022-06-23 09:48 UTC, johnnyshields commented
Please run Evergreen?

2022-06-24 07:20 UTC, p-mongo commented on spec/mongoid/indexable_spec.rb
> +        klass.index({ '$**': 1 }, wildcard_projection: { _id: 1, username: 0 })
What is preventing this line from existing in the model class?

2022-06-24 07:22 UTC, p-mongo commented on lib/mongoid/indexable/validators/options.rb
> +          :wildcard_projection
```suggestion
          :wildcard_projection,
```

2022-06-24 07:25 UTC, p-mongo commented
Hi @johnnyshields , thank you for the PR.

Can you please add a  test that verifies that the option is sent correctly as wildcardProjection. You can use EventSubscriber for this, here is an example of how to use it: https://github.com/mongodb/mongoid/blob/master/spec/mongoid/contextual/mongo_spec.rb#L909

2022-06-24 14:09 UTC, johnnyshields commented
Found the magic--turns out a PR is needed to mongo ruby driver to camelize the name. Will raise a PR there.

2022-06-24 14:45 UTC, johnnyshields commented
@p-mongo a change in Ruby Driver is needed to support the conversion of `wildcard_projection` to `wildcardProjection`. I have raised a PR for Ruby Driver here which **includes a test for that conversion**: https://github.com/mongodb/mongo-ruby-driver/pull/2541

I would propose to merge this PR as-is, and document the caveat in the release notes that "driver version XXX is required to use the alias".

The specs in this PR match what is in existence today for partial_filter_expression. It is worth nothing that Mongoid contains:
- no tests for end-to-end index creation for all options.
- no tests for index option aliases, such as `partial_filter_expression` to `partialFilterExpression`.

These are covered in the Ruby Driver tests, so Mongoid currently assumes the Ruby Driver works. If we wish to add such specs to Mongoid, I propose to do so in a follow-up ticket which covers *all indexes*.

2022-07-05 10:37 UTC, johnnyshields commented
@p-mongo you've marked this ticket as `oleg-responded`, however, my comments are still awaiting your response.

2022-07-14 16:30 UTC, johnnyshields commented
This PR is ready to merge:
- Ruby driver change is merged
- Tests are at coverage-parity with existing related features (`partial_filter_expression`)
- [MONGOID-5397](https://jira.mongodb.org/browse/MONGOID-5397) raised to cover future improvement of index tests, i.e. not specific to this PR.

2022-07-18 22:01 UTC, p-mongo requested changes

2022-07-18 22:01 UTC, p-mongo commented
This PR requires driver 2.18 to work, thus will go into Mongoid 8.0.

2022-07-19 05:42 UTC, johnnyshields commented on spec/mongoid/indexable/specification_spec.rb
> +                                 })
I've removed this, it wasn't needed.

2022-07-21 15:49 UTC, p-mongo approved these changes

2022-07-21 16:09 UTC, Neilshweky approved these changes
LGTM

2022-07-21 17:37 UTC, merged