MONGOID-5587 Auto encryption configuration
mongodb/mongoid pull request #5582
Opened 2023-03-23 15:45 UTC by comandeo

2023-03-24 15:00 UTC, jamis requested changes

2023-03-25 18:46 UTC, johnnyshields commented on spec/integration/encryption_spec.rb
> +  require_enterprise
It appears community edition server supports explicitly-declared encryption (i.e. not auto/schema map style)
https://www.mongodb.com/docs/manual/core/csfle/

2023-03-27 08:04 UTC, comandeo commented on lib/mongoid/config/encryption.rb
> +      def properties_for_relations(model, visited)
Forgot this one, thank you. Added.

2023-03-27 08:05 UTC, comandeo commented on lib/mongoid/config/encryption.rb
> +      def key_id_for(key_id)
Thank you. Also changed the signature to make it more clear, I hope.

2023-03-27 15:03 UTC, jamis approved these changes

2023-03-27 15:04 UTC, merged

2023-03-27 16:00 UTC, johnnyshields commented on spec/integration/encryption_spec.rb
> +  require_enterprise
Thank you for your clarification.

One more question: how exactly are schema maps applied? Does the user need to run a migration to apply the latest schema map to the DB? What if two different clients are using two different JSON schema map definitions with accessing the same database?

> What would be your use case where you need to be able to control everything from Rails?

I will need to see if there are any limitations with the auto-encryption approach when it is ready to test. For example, whether it allows me to encrypt existing unencrypted data seamlessly.