MONGOID-5617 - Increase performance of `Mongoid::Matcher#extract_attribute` by avoiding BSON::Document instantiation
mongodb/mongoid pull request #5630
Opened 2023-05-25 20:50 UTC by jasonpenny

https://jira.mongodb.org/browse/MONGOID-5617

`Mongoid::Matcher#extract_attribute` creates a `BSON::Document` for indifferent access of hash keys.

Performance can be improved by explicitly attempting string and symbol access.

```console
$ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [arm64-darwin21]

$ bundle exec ruby perf/benchmark_matches.rb 2>/dev/null
Warming up --------------------------------------
_matches? with BSON::Document
                         9.803k i/100ms
_matches? with indifferent key methods
                        15.212k i/100ms
Calculating -------------------------------------
_matches? with BSON::Document
                         97.544k (± 1.4%) i/s -    490.150k in   5.025882s
_matches? with indifferent key methods
                        153.542k (± 2.8%) i/s -    775.812k in   5.057118s

Comparison:
_matches? with indifferent key methods:   153542.2 i/s
_matches? with BSON::Document:    97544.2 i/s - 1.57x  slower
```

2023-06-13 07:31 UTC, comandeo requested changes
The PR looks very good, just some concerns should be addressed. Please let us know if you have capacity to clean the PR up.

2023-06-13 07:31 UTC, comandeo commented on perf/benchmark_matches.rb
> +    Mongoid::Matcher.instance_variable_set(:@attributes_as_bson_doc, true)
If we remove the old implementation of the matcher, we should remove the comparison, too.

2023-06-13 14:40 UTC, jasonpenny commented on lib/mongoid/matcher.rb
> +    @attributes_as_bson_doc = false
This was not intended to be kept, it was just for the benchmark

2023-06-13 16:11 UTC, jamis approved these changes
Looks great!

2023-06-14 07:23 UTC, comandeo approved these changes

2023-06-14 07:23 UTC, merged

2023-06-14 07:24 UTC, comandeo commented
Thank you very much for your contribution @jasonpenny