DOCSP-37059: Fix build errors
mongodb/mongoid pull request #5790
Opened 2024-02-23 16:34 UTC by norareidy

JIRA - https://jira.mongodb.org/browse/DOCSP-37059
Staging -

2024-02-23 17:12 UTC, jordan-smith721 requested changes
Just a few small changes

2024-02-23 17:12 UTC, jordan-smith721 commented on docs/release-notes/mongoid-9.0.txt
>    Time.zone = 'UTC'
```suggestion
   Time.zone = 'UTC'
```

2024-02-23 17:12 UTC, jordan-smith721 commented on docs/release-notes/mongoid-9.0.txt
>      -e 'puts ActiveSupport::TimeZone::MAPPING.keys'
```suggestion
   $ ruby -ractive_support/values/time_zone \
     -e 'puts ActiveSupport::TimeZone::MAPPING.keys'
```

2024-02-23 17:12 UTC, jordan-smith721 commented on docs/release-notes/mongoid-9.0.txt
>    Mongoid.legacy_persistence_context_behavior = true
```suggestion
   Mongoid.legacy_persistence_context_behavior = true
```

2024-02-23 17:12 UTC, jordan-smith721 commented on docs/tutorials/automatic-encryption.txt
> +<https://www.mongodb.com/docs/manual/core/queryable-encryption/reference/shared-library/#download-the-automatic-encryption-shared-library>`_
We have a tag for pages in the Server manual that is a bit shorter

```suggestion
:manual:`Automatic Encryption Shared Library for Queryable Encryption 
</core/queryable-encryption/reference/shared-library/#download-the-automatic-encryption-shared-library>`
```

2024-02-23 17:12 UTC, jordan-smith721 commented on docs/tutorials/automatic-encryption.txt
> +  page in the Server manual. These limitations also apply to Mongoid.
```suggestion
  :manual:`CSFLE Limitations </core/csfle/reference/limitations/>`
  page in the Server manual. These limitations also apply to Mongoid.
```

2024-02-26 19:26 UTC, alexbevi approved these changes
LGTM

2024-02-26 19:26 UTC, merged